# Generated by Django 4.2.16 on 2024-09-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='price_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_on_one', models.DecimalField(decimal_places=2, default=25.0, max_digits=5)),
                ('two_on_one', models.DecimalField(decimal_places=2, default=35.0, max_digits=5)),
                ('three_on_one', models.DecimalField(decimal_places=2, default=45.0, max_digits=5)),
            ],
        ),
    ]
